# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://www.mpi-forum.org"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project
#repository: https://github.com/mpi-forum/mpi-forum.github.io

# Name of website
title: MPI Forum

# Short description of your site
description: This website contains information about the activities of the MPI Forum, which is the standardization forum for the Message Passing Interface (MPI).

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
    Docs: "docs/"
    Current MPI Efforts:
        - MPI 5.0: "mpi-50/"
        - MPI 4.1: "mpi-41/"
    Past MPI Standard Efforts:
        - MPI 4.0: "mpi-40/"
        - MPI 3.1: "mpi-31/"
        - MPI 3.0: "mpi-30/"
        - MPI 2.2: "mpi-22/"
        - MPI 2.1: "mpi-21/"
        - MPI 2.0: "mpi-20/"
    Meetings:
        - Voting Meetings: "meetings"
        - Virtual Meetings: "virtual_meetings"
    Resources:
        - GitHub: "https://www.github.com/mpi-forum/"
        - Mailing Lists: "http://lists.mpi-forum.org"
        - Make Comments: "comments/"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar-icon.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
#author:
  #name: Wesley Bland
  #email: "youremail@domain.com"
  #facebook: yourname  # eg. daattali
  #github: yourname    # eg. daattali
  #twitter: yourname   # eg. daattali
  #linkedin: yourname  # eg. daattali
  #xing: yourname      # eg. daattali
  #stackoverflow: yourlink  # eg. "3943160/daattali"
  #instagram: yourname # eg. daattali
  #youtube: yourlink # eg. user/daattali or channel/daattali

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: false
  xing: false
  stackoverflow: false
  instagram: false
  youtube: false

# Select which share links to show in posts
share-links-active:
  twitter: false
  facebook: false
  google: false
  linkedin: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
#url-pretty: "MyWebsite.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-110855000-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Chicago"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: false # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
